DROP TABLE IF EXISTS users;

-- Vytvoř tabulku s UUID
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
  firstname VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  passhash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

DROP TABLE IF EXISTS products
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
  barcode VARCHAR(255) NOT NULL,
  productName VARCHAR(125) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS warehouse (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_uuid CHAR(36) NOT NULL UNIQUE,
  product_in INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_uuid) REFERENCES products(uuid) ON DELETE CASCADE
) ENGINE=InnoDB;



