

CREATE TABLE IF NOT EXISTS users (
  uuid CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  firstname VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  passhash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS products (
  uuid CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  barcode VARCHAR(255) NOT NULL UNIQUE,
  productName VARCHAR(125) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS warehouse (
  uuid CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  product_uuid CHAR(36) NOT NULL UNIQUE,
  product_in INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_uuid) REFERENCES products(uuid) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS stocking (
  uuid CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
  user_uuid CHAR(36) NOT NULL,
  product_uuid CHAR(36) NOT NULL,
  quantity INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_uuid) REFERENCES users(uuid) ON DELETE CASCADE,
  FOREIGN KEY (product_uuid) REFERENCES products(uuid) ON DELETE CASCADE
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS picking (
  uuid CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
  user_uuid CHAR(36) NOT NULL,
  product_uuid CHAR(36) NOT NULL,
  quantity INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_uuid) REFERENCES users(uuid) ON DELETE CASCADE,
  FOREIGN KEY (product_uuid) REFERENCES products(uuid) ON DELETE CASCADE
) ENGINE=InnoDB;

